<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends EntityRepository
{
    public function dateDiffExperience()
    {
        $qb = $this->createQueryBuilder('e');

//        , DATE_DIFF(e.endAt, e.beginAt)

        $qb->select('e, e.beginAt, e.endAt')
            ->orderBy('e.endAt', 'DESC');

        $resultstemp = $qb->getQuery()->getResult();

        $results = '';
        foreach ($resultstemp as $result){
//            $beginAtYears =
//            $beginAtMonths =
//            $beginAtDays = ;

//            $endAtYears =
//            $endAtMonths =
//            $endAtDays =

            $result[1]['diffYears'] = $result['beginAt']->format('Y') - $result['endAt']->format('Y');
            $result[1]['diffMonths'] = $result['beginAt']->format('m') - $result['endAt']->format('m');;
            $result[1]['diffDays'] = $result['beginAt']->format('d') - $result['endAt']->format('d');

            $results[] = $result;
//            var_dump($result);die;

        }
//        var_dump($results);die;
        return $results;
    }
}
