<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends EntityRepository
{
    public function dateDiffExperience()
    {
        $qb = $this->createQueryBuilder('e');

        $qb->select('e, e.beginAt, e.endAt')
            ->orderBy('e.endAt', 'DESC');

        $resultstemp = $qb->getQuery()->getResult();

        $results = '';
        foreach ($resultstemp as $result){
            $result[1]['diffYears'] = $result['beginAt']->format('Y') - $result['endAt']->format('Y');
            $result[1]['diffMonths'] = $result['beginAt']->format('m') - $result['endAt']->format('m');;
            $result[1]['diffDays'] = $result['beginAt']->format('d') - $result['endAt']->format('d');

            $results[] = $result;
        }

        return $results;
    }
}
