<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends EntityRepository
{
    public function experiences(){
        $qb = $this->createQueryBuilder('e');

        $qb->select('e, DATE_DIFF(e.endAt, e.beginAt)' )
            ->orderBy('e.endAt', 'DESC');

        $result = $qb->getQuery()->getResult();

//        dump($result);die;
    }
}
